import type { NearbyDieselStation } from "@/lib/nearby";
type M={id:string|null;lat:string;lon:string;logo?:string|null;cluster_count?:string|null};
const MAP="https://bg.fuelo.net/ajax/get_gasstations_within_bounds_mysql_clustering",INFO="https://bg.fuelo.net/ajax/get_infowindow_content";
const num=(v:string|null|undefined)=>{const n=Number((v??"").replace(",","."));return Number.isFinite(n)?n:null};
const dist=(a:number,b:number,c:number,d:number)=>{const x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,q=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return 6371*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))};
const brands:Record<string,string>={lukoil:"Lukoil",petrol:"Petrol",omv:"OMV",shell:"Shell",eko:"EKO",rompetrol:"Rompetrol",apid2000:"APID 2000",insa:"INSA OIL","ek-petrol":"EK Petrol"};
async function get<T>(u:string,o?:RequestInit){const r=await fetch(u,{...o,headers:{Accept:"application/json","User-Agent":"FuelTrackerBG/1.0",...(o?.headers??{})},cache:"no-store",signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error(String(r.status));return r.json() as Promise<T>}
function split(b:{a:number;b:number;c:number;d:number;z:number;n:number}){const x=(b.a+b.b)/2,y=(b.c+b.d)/2,n=b.n+1,z=Math.min(18,b.z+2);return[{a:b.a,b:x,c:b.c,d:y,z,n},{a:b.a,b:x,c:y,d:b.d,z,n},{a:x,b:b.b,c:b.c,d:y,z,n},{a:x,b:b.b,c:y,d:b.d,z,n}]}
async function discover(lat:number,lon:number,r:number){const la=r/110.574,lo=r/(111.32*Math.max(.25,Math.cos(lat*Math.PI/180))),q=[{a:lat-la,b:lat+la,c:lon-lo,d:lon+lo,z:r<=5?13:r<=10?12:11,n:0}],u=new Map<string,M>(),md=r<=5?4:r<=25?3:2;while(q.length&&u.size<2500){const b=q.shift()!;try{const x=await get<{status:string;gasstations?:M[]}>(MAP,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded; charset=UTF-8"},body:new URLSearchParams({lat_max:String(b.b),lon_max:String(b.d),lat_min:String(b.a),lon_min:String(b.c),zoom:String(b.z),country:"bg",fuel:"diesel",brand:"all"})});let dense=false;for(const m of x.gasstations??[]){if(m.id)u.set(m.id,m);if(!m.id&&Number(m.cluster_count??1)>1)dense=true}if(dense&&b.n<md)q.push(...split(b))}catch{if(b.n<md)q.push(...split(b))}}return[...u.values()].map(m=>({m,lat:num(m.lat),lon:num(m.lon)})).filter(x=>x.lat!=null&&x.lon!=null).map(x=>({...x,d:dist(lat,lon,x.lat!,x.lon!)})).filter(x=>x.d<=r).sort((a,b)=>a.d-b.d)}
const clean=(s:string)=>s.replace(/<[^>]*>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/\\s+/g," ").trim();
export async function liveNearbyDiesel(lat:number,lon:number,r=25,limit=10):Promise<NearbyDieselStation[]>{const ms=await discover(lat,lon,r),out:NearbyDieselStation[]=[];let cur=0;async function worker(){while(true){const i=cur++;if(i>=ms.length)return;const x=ms[i];if(!x.m.id)continue;try{const z=await get<{status:string;text?:string}>(`${INFO}/${encodeURIComponent(x.m.id)}?lang=bg`);if(z.status!=="OK"||!z.text)continue;const h=z.text,name=clean(h.match(/<h4[^>]*>([\\s\\S]*?)<\\/h4>/i)?.[1]??""),loc=clean(h.match(/<h5[^>]*>([\\s\\S]*?)<\\/h5>/i)?.[1]??""),price=num(h.match(/title=["']Diesel:\s*([0-9]+(?:[.,][0-9]+)?)\s*€/л/i)?.[1]);if(!name||!loc||price==null)continue;const p=loc.split(",").map(s=>s.trim()).filter(Boolean);out.push({id:x.m.id,name,brand:x.m.logo?brands[x.m.logo.toLowerCase()]??x.m.logo:null,city:p.at(-1)??"България",address:p.slice(1).join(", ")||p.at(-1)||"България",price,observedAt:new Date(),confidence:70,sourceUrl:`https://bg.fuelo.net/gasstation/id/${x.m.id}?lang=bg`,latitude:x.lat!,longitude:x.lon!,distanceKm:Number(x.d.toFixed(2))})}catch{}}}await Promise.all(Array.from({length:Math.min(10,Math.max(1,ms.length))},worker));return out.sort((a,b)=>a.price-b.price||a.distanceKm-b.distanceKm).slice(0,Math.max(limit,1000))}
